apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canary-bot.fullname" . }}
  labels:
    {{- include "canary-bot.labels" . | nindent 4 }}
data:
{{- with .Values.mesh }}
  {{- toYaml . | nindent 2 }}
{{- end }}
