apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "canary-bot.fullname" . }}
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "canary-bot.fullname" . }}
  policyTypes:
  - Egress
