apiVersion: v1
kind: Service
metadata:
  name: {{ include "canary-bot.fullname" . }}
  labels:
    {{- include "canary-bot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: apiport
      port: {{ .Values.service.api.port | default "8080" }}
      targetPort: {{ .Values.service.api.targetPort | default "8080" }}
    - name: meshport
      port: {{ .Values.service.mesh.port | default "8081" }}
      targetPort: {{ .Values.service.mesh.port | default "8081" }}
  selector:
    {{- include "canary-bot.selectorLabels" . | nindent 4 }}
