# https://github.com/marketplace/actions/actions-k3s
name: Helm Testing
on:
  push:
    paths:
      - chart/**
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: debianmaster/actions-k3s@master
      id: k3s
      with:
        version: 'v1.21.2-k3s1'
    - run: |
        kubectl get nodes
        helm lint .
